name: Test
on:
  push:
env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup Cargo dependency cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: shared

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: -Dwarnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Setup Cargo dependency cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: shared

      - name: Run tests
        run: cargo test --all-targets --all-features --verbose

      - name: Run doc tests
        run: cargo test --doc --all-features

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Cargo dependency cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: shared

      - name: Build project
        run: cargo build --verbose
